// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLR5wW6Ayhid0tABIF2NX3ZtWTIOAgBPE',
    appId: '1:551211055428:web:9530617298ff4cd0e3bf11',
    messagingSenderId: '551211055428',
    projectId: 'chat-app-e4ca9',
    authDomain: 'chat-app-e4ca9.firebaseapp.com',
    storageBucket: 'chat-app-e4ca9.appspot.com',
    measurementId: 'G-DTKN9CXR7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4y3kZwrC8IwklgYYbCLmeL-S5XpEOBgk',
    appId: '1:551211055428:android:3671394ed274f11ce3bf11',
    messagingSenderId: '551211055428',
    projectId: 'chat-app-e4ca9',
    storageBucket: 'chat-app-e4ca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDFPxqTQxkYcAc2n9xGyFEbQaw3xT-HqM',
    appId: '1:551211055428:ios:c4f402328ed319ffe3bf11',
    messagingSenderId: '551211055428',
    projectId: 'chat-app-e4ca9',
    storageBucket: 'chat-app-e4ca9.appspot.com',
    iosBundleId: 'com.example.newChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDFPxqTQxkYcAc2n9xGyFEbQaw3xT-HqM',
    appId: '1:551211055428:ios:c4f402328ed319ffe3bf11',
    messagingSenderId: '551211055428',
    projectId: 'chat-app-e4ca9',
    storageBucket: 'chat-app-e4ca9.appspot.com',
    iosBundleId: 'com.example.newChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLR5wW6Ayhid0tABIF2NX3ZtWTIOAgBPE',
    appId: '1:551211055428:web:1f412ea16d7bad81e3bf11',
    messagingSenderId: '551211055428',
    projectId: 'chat-app-e4ca9',
    authDomain: 'chat-app-e4ca9.firebaseapp.com',
    storageBucket: 'chat-app-e4ca9.appspot.com',
    measurementId: 'G-YQ6Q2SDY2C',
  );
}
